SELECT 
    COLUMN_NAME AS [Field],
    DATA_TYPE AS [Type],
    IS_NULLABLE AS [Null],
    COLUMN_DEFAULT AS [Default]
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_CATALOG = DB_NAME()
    AND TABLE_NAME = 'books'
ORDER BY 
    ORDINAL_POSITION;

